from abc import ABC, abstractmethod


class LLMProvider(ABC):
    """
    Common interface for all LLM providers used by InboxPilot.

    Every LLM provider must implement the generate() method.
    """

    @abstractmethod
    def generate(
        self,
        system_prompt: str,
        user_prompt: str,
    ) -> str:
        """
        Generate a response from the LLM.

        Args:
            system_prompt: Instructions that define the
                behavior of the model.
            user_prompt: The actual task/input.

        Returns:
            Raw text response generated by the LLM.
        """
        raise NotImplementedError