"""add_user_id_to_emails

Revision ID: 12bf4c86c7de
Revises: 8e62b34330d1
Create Date: 2026-09-23 11:27:33.265510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12bf4c86c7de'
down_revision: Union[str, Sequence[str], None] = '8e62b34330d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('user_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_emails_user_id'), 'emails', ['user_id'], unique=False)
    op.create_foreign_key('fk_emails_user_id', 'emails', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_emails_user_id', 'emails', type_='foreignkey')
    op.drop_index(op.f('ix_emails_user_id'), table_name='emails')
    op.drop_column('emails', 'user_id')
    # ### end Alembic commands ###
