"""Add telegram_message_id to action_approvals

Revision ID: 5cdca0d42453
Revises: 12bf4c86c7de
Create Date: 2026-09-23 21:49:01.766274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cdca0d42453'
down_revision: Union[str, Sequence[str], None] = '12bf4c86c7de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('action_approvals', sa.Column('telegram_message_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('action_approvals', 'telegram_message_id')
    # ### end Alembic commands ###
