"""Add_UserSettings

Revision ID: 6f9ad7b2216d
Revises: 5cdca0d42453
Create Date: 2026-09-24 23:46:54.485836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f9ad7b2216d'
down_revision: Union[str, Sequence[str], None] = '5cdca0d42453'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_settings',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('notify_email_approvals', sa.Boolean(), nullable=False),
    sa.Column('notify_email_completions', sa.Boolean(), nullable=False),
    sa.Column('notify_email_failures', sa.Boolean(), nullable=False),
    sa.Column('notify_email_alerts', sa.Boolean(), nullable=False),
    sa.Column('notify_telegram_approvals', sa.Boolean(), nullable=False),
    sa.Column('notify_telegram_completions', sa.Boolean(), nullable=False),
    sa.Column('notify_telegram_failures', sa.Boolean(), nullable=False),
    sa.Column('automation_mode', sa.String(), nullable=False),
    sa.Column('confidence_threshold', sa.Integer(), nullable=False),
    sa.Column('pause_all_automations', sa.Boolean(), nullable=False),
    sa.Column('approval_required_sending', sa.Boolean(), nullable=False),
    sa.Column('approval_required_forwarding', sa.Boolean(), nullable=False),
    sa.Column('approval_required_deleting', sa.Boolean(), nullable=False),
    sa.Column('approval_required_calendar', sa.Boolean(), nullable=False),
    sa.Column('approval_required_other', sa.Boolean(), nullable=False),
    sa.Column('theme', sa.String(), nullable=False),
    sa.Column('density', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_settings')
    # ### end Alembic commands ###
