"""Add user_id to integrations

Revision ID: 8e62b34330d1
Revises: 0312dc696876
Create Date: 2026-09-22 21:43:36.760685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e62b34330d1'
down_revision: Union[str, Sequence[str], None] = '0312dc696876'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Delete existing orphaned integration data to prevent type cast / constraint errors
    op.execute("DELETE FROM telegram_connections")
    op.execute("DELETE FROM google_accounts")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('google_accounts', sa.Column('user_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_google_accounts_user_id'), 'google_accounts', ['user_id'], unique=False)
    op.create_foreign_key(None, 'google_accounts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('telegram_connections_user_id_fkey', 'telegram_connections', type_='foreignkey')
    op.alter_column('telegram_connections', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.create_foreign_key(None, 'telegram_connections', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'telegram_connections', type_='foreignkey')
    op.create_foreign_key(op.f('telegram_connections_user_id_fkey'), 'telegram_connections', 'google_accounts', ['user_id'], ['id'])
    op.alter_column('telegram_connections', 'user_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'google_accounts', type_='foreignkey')
    op.drop_index(op.f('ix_google_accounts_user_id'), table_name='google_accounts')
    op.drop_column('google_accounts', 'user_id')
    # ### end Alembic commands ###
