"""Add error_message to Email

Revision ID: 920121b62edb
Revises: 6f9ad7b2216d
Create Date: 2026-10-05 21:41:28.192604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '920121b62edb'
down_revision: Union[str, Sequence[str], None] = '6f9ad7b2216d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('error_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emails', 'error_message')
    # ### end Alembic commands ###
